### ISSUE TITLE
link to yunohost documatition is incorrect

### ISSUE THREAD

**Issue by jeanpalaz** [lunarok/camera_ynh#1]
Hello,

I have a Raspberry PI with cam and Ynohost installed. I would like to use it, then I found your plugin.
I read yourd documentaiton but in REDAME.md the link to Yunohost documentaiton is not correct.
Could you provide a good link or insert the documenation in README.md, please.

THX for sharing the package.
Jean

**Comment by lunarok** [comment]
Just done sometime ago for own usage with jeedom, not really working

**Comment by rzr** [comment]
I am using it along motion
